language: python

jobs:
  include:
    - stage: build
      script./test
    - stage: test
      script: ./test 
    - # stage name not required, will continue to use `test`
      script: ./test 
    - stage: deploy
      script: ./deploy

python:
  - "2.7"

script: 
  - python hello.py
