language: python

jobs:
  include:
    - stage: test
      script: ./test 
    - # stage name not required, will continue to use `test`
      script: ./test 
    - stage: deploy
      script: ./deploy

branches:
  only:
  - master

python:

  - "2.7"

script: 

  - python hello.py
